services:
  # C++ シミュレータ
  simulator-cpp:
    build:
      context: ./simulator
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/simulator:/app
    working_dir: /app
    tty: true

  # フロントエンド
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/frontend:/app
      - /app/node_modules
    working_dir: /app
    tty: true
    environment:
      - WATCHPACK_POLLING=true