services:
  # C++ シミュレータ
  simulator-cpp:
    build:
      context: ./simulator
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/simulator:/app
      - ${LOCAL_WORKSPACE_FOLDER:-.}/frontend/src/wasm:/app/build_wasm/out
    working_dir: /app
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  # フロントエンド
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/frontend:/app
      - /app/node_modules
    working_dir: /app
    tty: true
    environment:
      - WATCHPACK_POLLING=true